version: '3'
services:
  magento:
    image: magestore/mftf:2.2.6-apache-php7.1
    volumes:
      - ./server/app/code/Magestore:/var/www/html/app/code/Magestore
    ports:
      - 8080-8089:80
    environment:
      BASE_URL: https://localhost.com/
      MAGENTO_DEV_MODE: developer
    networks:
      webnet:
        aliases:
          - localhost.com

  db:
    image: magestore/mftf-db:2.2.6
    environment:
      MYSQL_ROOT_PASSWORD: magento
    volumes:
      - ../db/conf.d:/etc/my.cnf.d
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8060-8069:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: magento
    networks:
      - webnet

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8020-8029:8025
    networks:
      - webnet

networks:
  webnet:
